allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js-pure: true
  esbuild: true
  msw: true
  nx: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
