/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTeamsRouteImport } from './routes/_authed/teams'
import { Route as AuthedStandingsRouteImport } from './routes/_authed/standings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as AuthedTeamsCodeRouteImport } from './routes/_authed/teams.$code'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeamsRoute = AuthedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStandingsRoute = AuthedStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamsCodeRoute = AuthedTeamsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AuthedTeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/chat': typeof AuthedChatRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/standings': typeof AuthedStandingsRoute
  '/teams': typeof AuthedTeamsRouteWithChildren
  '/teams/$code': typeof AuthedTeamsCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/chat': typeof AuthedChatRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/standings': typeof AuthedStandingsRoute
  '/teams': typeof AuthedTeamsRouteWithChildren
  '/teams/$code': typeof AuthedTeamsCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/standings': typeof AuthedStandingsRoute
  '/_authed/teams': typeof AuthedTeamsRouteWithChildren
  '/_authed/teams/$code': typeof AuthedTeamsCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/chat'
    | '/dashboard'
    | '/standings'
    | '/teams'
    | '/teams/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/chat'
    | '/dashboard'
    | '/standings'
    | '/teams'
    | '/teams/$code'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/_authed/chat'
    | '/_authed/dashboard'
    | '/_authed/standings'
    | '/_authed/teams'
    | '/_authed/teams/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teams': {
      id: '/_authed/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthedTeamsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/standings': {
      id: '/_authed/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthedStandingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/teams/$code': {
      id: '/_authed/teams/$code'
      path: '/$code'
      fullPath: '/teams/$code'
      preLoaderRoute: typeof AuthedTeamsCodeRouteImport
      parentRoute: typeof AuthedTeamsRoute
    }
  }
}

interface AuthedTeamsRouteChildren {
  AuthedTeamsCodeRoute: typeof AuthedTeamsCodeRoute
}

const AuthedTeamsRouteChildren: AuthedTeamsRouteChildren = {
  AuthedTeamsCodeRoute: AuthedTeamsCodeRoute,
}

const AuthedTeamsRouteWithChildren = AuthedTeamsRoute._addFileChildren(
  AuthedTeamsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedStandingsRoute: typeof AuthedStandingsRoute
  AuthedTeamsRoute: typeof AuthedTeamsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedStandingsRoute: AuthedStandingsRoute,
  AuthedTeamsRoute: AuthedTeamsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
